[package]
name = "esoteric-vm"
version = "0.1.0"
edition = "2021"
repository = "https://www.github.com/tadaHrd/esoteric-vm"

[dependencies]
crossterm = { version = "0.28.1", features = ["events", "windows"] }
strum = { version = "0.26.3", features = ["derive"] }